# Generated by Django 5.1.1 on 2024-12-28 22:41

import converter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(storage=converter.models.OverwriteStorage(), upload_to='uploads/')),
                ('output_file', models.FileField(blank=True, null=True, storage=converter.models.OverwriteStorage(), upload_to='converted/')),
                ('source_format', models.CharField(max_length=10)),
                ('target_format', models.CharField(max_length=10)),
                ('converted', models.BooleanField(default=False)),
            ],
        ),
    ]
