# Generated by Django 5.1.1 on 2024-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
